substitutions:
  device_name: "Air sensor"
  friendly_name: "Air sensor"
  device_description: "Ikea Vindriktning + ESP8266 + BME680"
  #icon: "mdi:washing-machine"

esphome:
  name: "${device_name}"
  comment: "${device_description}"
  platform: ESP8266
  board: d1_mini

ota:
  - platform: esphome

safe_mode:
  disabled: true

# Enable logging
logger:
  level: DEBUG

mdns:
  disabled: false

# Enable Home Assistant API
api:

web_server:
  port: 80
  local: true
  ota: false
  include_internal: false

wifi:
  power_save_mode: none
  output_power: 20.0
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  use_address: 172.16.1.39
  
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "Air sensor Hotspot"
    password: !secret hotspot_password

captive_portal:

i2c:
  scl: GPIO12 #D6
  sda: GPIO13 #D7
  scan: True
  id: bus_a

bme680_bsec:
  address: 0x76
  sample_rate: ulp

# Ikea Vindriktning PM2.5 sensor
uart:
  rx_pin: D2
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "${friendly_name} Particule PM2.5"
      id: pm_2_5
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 50
            send_every: 10
      disabled_by_default: false
      internal: false
  - platform: bme680_bsec
    temperature:
      name: "${friendly_name} Temperatură"
      accuracy_decimals: 2
      filters:
        offset: -2.6
      disabled_by_default: false
      internal: false
    pressure:
      name: "${friendly_name} Presiune"
      accuracy_decimals: 2
      unit_of_measurement: "mmHg"
      filters:
         - multiply: 0.75006375541921
      disabled_by_default: false
      internal: false
    humidity:
      name: "${friendly_name} Umiditate"
      accuracy_decimals: 2
      disabled_by_default: false
      internal: false
      filters:
        offset: 10.5
    gas_resistance:
      name: "${friendly_name} Rezistență Gaz"
      accuracy_decimals: 2
      disabled_by_default: false
      internal: false
    iaq:
      name: "${friendly_name} Nivel IAQ"
      id: iaq
      accuracy_decimals: 2
      disabled_by_default: false
      internal: false
    co2_equivalent:
      name: "${friendly_name} Particule CO2"
      accuracy_decimals: 2
      disabled_by_default: false
      internal: false
    breath_voc_equivalent:
      name: "${friendly_name} VOC Equivalent"
      accuracy_decimals: 2
      disabled_by_default: false
      internal: false

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "${friendly_name} IAQ Acuratețe"
      disabled_by_default: false
      internal: false

  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: false
      internal: false

  - platform: template
    name: "${friendly_name} Nivel CO2"
    disabled_by_default: false
    internal: false
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excelent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Bun"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Poluare ușoară"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Poluare moderată"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Poluare mare"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Poluare severă"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Poluare extremă"};
      }
      else {
        return {"error"};
      }

  - platform: template
    name: "${friendly_name} Nivel PM2.5"
    disabled_by_default: false
    internal: false
    icon: "mdi:blur"
    lambda: |-
      if ( int(id(pm_2_5).state) <= 25) {
        return {"Excelent"};
      }
      else if (int(id(pm_2_5).state) >= 26 && int(id(pm_2_5).state) <= 50) {
        return {"Corect"};
      }
      else if (int(id(pm_2_5).state) >= 51 && int(id(pm_2_5).state) <= 100) {
        return {"Poluat"};
      }
      else if (int(id(pm_2_5).state) >= 101 && int(id(pm_2_5).state) <= 300) {
        return {"Foarte poluat"};
      }
      else if (int(id(pm_2_5).state) >= 301) {
        return {"Poluare extremă"};
      }
      else {
        return {"error"};
      }

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"
  - platform: factory_reset
    name: "${friendly_name} Reset to Factory Settings"
    disabled_by_default: false
    internal: false
    id: Reset
    